name: actions

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup (1/2)
        run: |
          chmod +x ${{github.workspace}}/setup.sh
          sudo ${{github.workspace}}/setup.sh
      - name: Setup (2/2)
        uses: ros-tooling/setup-ros@v0.6
        with:
          required-ros-distributions: humble
      - id: build
        name: Build
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: humble
          package-name: hyper_variables
      - name: Publish
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: ${{steps.build.outputs.ros-workspace-directory-name}}/build/hyper_variables/test_results/hyper_variables/hyper_variables_tests.gtest.xml
          check_name: tests
