name: actions

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: |
          chmod +x ${{github.workspace}}/install.sh
          sudo ${{github.workspace}}/install.sh

      - name: Configure
        run: mkdir build && cd build && cmake ..

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: make -j$(nproc)

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ./apps/tests/HyperVariablesTests --gtest_output="xml:${{github.workspace}}/tests/junit/results.xml"

      - name: Publish
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: "tests/junit/*.xml"
          check_name: "tests"
